from enum import Enum


class SpotType(Enum):
    DISABLED = "DISABLED"
    WORKERS = "WORKERS"
    VISITORS = "VISITORS"
    ELECTRIC_VEHICLES = "ELECTRIC_VEHICLES"
    MANAGEMENT = "MANAGEMENT"
    GENERAL = "GENERAL"


class SpotStatus(Enum):
    AVAILABLE = "AVAILABLE"
    OCCUPIED = "OCCUPIED"
    RESERVED = "RESERVED"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"


class LotStatus(Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    FULL = "FULL"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"


class LotType(Enum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"


class LocationType(Enum):
    MALL = "MALL"
    OFFICE = "OFFICE"
    AIRPORT = "AIRPORT"
    HOSPITAL = "HOSPITAL"
    RESIDENTIAL = "RESIDENTIAL"
