name: checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: astral-sh/setup-uv@v10.0.0
        with:
          enable-cache: true

      - run: make install
      - run: make check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
